require("dotenv").config();
const connectDB = require("./config/db");
const Product = require("./models/Product");

// NOTE: image paths below (e.g. /assets/products/shoes/s1.jpg) point to
// real product photos in client/public/assets/products/ — run
// "npm run download-images" once from the project root to fetch them.
const products = [
  // SHOES
  { name: "Men Classic Running Sneakers", category: "shoes", gender: "men", price: 1299, oldPrice: 2199, image: "/assets/products/shoes/s1.jpg", tag: "New", rating: 3.8, reviewCount: 45, material: "Genuine leather & breathable mesh upper with a cushioned rubber sole", sizes: ["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"] },
  { name: "Men Leather Chelsea Boots", category: "shoes", gender: "men", price: 1549, oldPrice: 2649, image: "/assets/products/shoes/s2.jpg", tag: "Best Seller", rating: 3.9, reviewCount: 58, material: "Genuine leather & breathable mesh upper with a cushioned rubber sole", sizes: ["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"] },
  { name: "Men Casual Canvas Shoes", category: "shoes", gender: "men", price: 1799, oldPrice: 3099, image: "/assets/products/shoes/s3.jpg", tag: "Trending", rating: 4.0, reviewCount: 71, material: "Genuine leather & breathable mesh upper with a cushioned rubber sole", sizes: ["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"] },
  { name: "Men Suede Desert Boots", category: "shoes", gender: "men", price: 2049, oldPrice: 2949, image: "/assets/products/shoes/s4.jpg", tag: "", rating: 4.1, reviewCount: 84, material: "Genuine leather & breathable mesh upper with a cushioned rubber sole", sizes: ["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"] },
  { name: "Men Sports Training Shoes", category: "shoes", gender: "men", price: 2299, oldPrice: 3399, image: "/assets/products/shoes/s5.jpg", tag: "New", rating: 4.2, reviewCount: 97, material: "Genuine leather & breathable mesh upper with a cushioned rubber sole", sizes: ["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"] },
  { name: "Men Formal Oxford Shoes", category: "shoes", gender: "men", price: 2549, oldPrice: 3849, image: "/assets/products/shoes/s6.jpg", tag: "", rating: 4.3, reviewCount: 110, material: "Genuine leather & breathable mesh upper with a cushioned rubber sole", sizes: ["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"] },
  { name: "Men High-Top Skate Sneakers", category: "shoes", gender: "men", price: 2799, oldPrice: 3699, image: "/assets/products/shoes/s7.jpg", tag: "Best Seller", rating: 4.4, reviewCount: 123, material: "Genuine leather & breathable mesh upper with a cushioned rubber sole", sizes: ["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"] },
  { name: "Men Mesh Walking Shoes", category: "shoes", gender: "men", price: 3049, oldPrice: 4149, image: "/assets/products/shoes/s8.jpg", tag: "", rating: 4.5, reviewCount: 136, material: "Genuine leather & breathable mesh upper with a cushioned rubber sole", sizes: ["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"] },
  { name: "Women Platform Sneakers", category: "shoes", gender: "women", price: 1499, oldPrice: 2799, image: "/assets/products/shoes/s9.jpg", tag: "New", rating: 4.6, reviewCount: 149, material: "Genuine leather & breathable mesh upper with a cushioned rubber sole", sizes: ["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"] },
  { name: "Women Strappy Block Heels", category: "shoes", gender: "women", price: 1749, oldPrice: 2649, image: "/assets/products/shoes/s10.jpg", tag: "Best Seller", rating: 4.7, reviewCount: 162, material: "Genuine leather & breathable mesh upper with a cushioned rubber sole", sizes: ["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"] },
  { name: "Women Ballet Flats", category: "shoes", gender: "women", price: 1999, oldPrice: 3099, image: "/assets/products/shoes/s11.jpg", tag: "Trending", rating: 4.8, reviewCount: 175, material: "Genuine leather & breathable mesh upper with a cushioned rubber sole", sizes: ["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"] },
  { name: "Women Ankle Strap Sandals", category: "shoes", gender: "women", price: 2249, oldPrice: 3549, image: "/assets/products/shoes/s12.jpg", tag: "", rating: 4.9, reviewCount: 188, material: "Genuine leather & breathable mesh upper with a cushioned rubber sole", sizes: ["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"] },
  { name: "Women Knee-High Boots", category: "shoes", gender: "women", price: 2499, oldPrice: 3399, image: "/assets/products/shoes/s13.jpg", tag: "New", rating: 3.8, reviewCount: 201, material: "Genuine leather & breathable mesh upper with a cushioned rubber sole", sizes: ["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"] },
  { name: "Women Espadrille Wedges", category: "shoes", gender: "women", price: 2749, oldPrice: 3849, image: "/assets/products/shoes/s14.jpg", tag: "", rating: 3.9, reviewCount: 214, material: "Genuine leather & breathable mesh upper with a cushioned rubber sole", sizes: ["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"] },
  { name: "Women Slip-On Loafers", category: "shoes", gender: "women", price: 2999, oldPrice: 4299, image: "/assets/products/shoes/s15.jpg", tag: "Best Seller", rating: 4.0, reviewCount: 227, material: "Genuine leather & breathable mesh upper with a cushioned rubber sole", sizes: ["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"] },
  { name: "Women Running Shoes", category: "shoes", gender: "women", price: 1449, oldPrice: 2349, image: "/assets/products/shoes/s16.jpg", tag: "", rating: 4.1, reviewCount: 240, material: "Genuine leather & breathable mesh upper with a cushioned rubber sole", sizes: ["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"] },

  // DRESSES
  { name: "Men Nehru Collar Kurta Set", category: "dresses", gender: "men", price: 1299, oldPrice: 1999, image: "/assets/products/dresses/d1.jpg", tag: "New", rating: 3.8, reviewCount: 45, material: "Premium breathable fabric blend with a tailored, easy-care finish", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
  { name: "Men Linen Resort Shirt Set", category: "dresses", gender: "men", price: 1529, oldPrice: 2429, image: "/assets/products/dresses/d2.jpg", tag: "Best Seller", rating: 3.9, reviewCount: 58, material: "Premium breathable fabric blend with a tailored, easy-care finish", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
  { name: "Men Sherwani Set", category: "dresses", gender: "men", price: 1759, oldPrice: 2859, image: "/assets/products/dresses/d3.jpg", tag: "Trending", rating: 4.0, reviewCount: 71, material: "Premium breathable fabric blend with a tailored, easy-care finish", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
  { name: "Men Bandhgala Ethnic Set", category: "dresses", gender: "men", price: 1989, oldPrice: 2689, image: "/assets/products/dresses/d4.jpg", tag: "", rating: 4.1, reviewCount: 84, material: "Premium breathable fabric blend with a tailored, easy-care finish", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
  { name: "Men Cotton Kurta Pajama", category: "dresses", gender: "men", price: 2219, oldPrice: 3119, image: "/assets/products/dresses/d5.jpg", tag: "New", rating: 4.2, reviewCount: 97, material: "Premium breathable fabric blend with a tailored, easy-care finish", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
  { name: "Men Silk Blend Ethnic Jacket Set", category: "dresses", gender: "men", price: 2449, oldPrice: 3549, image: "/assets/products/dresses/d6.jpg", tag: "", rating: 4.3, reviewCount: 110, material: "Premium breathable fabric blend with a tailored, easy-care finish", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
  { name: "Men Printed Kurta Set", category: "dresses", gender: "men", price: 2679, oldPrice: 3379, image: "/assets/products/dresses/d7.jpg", tag: "Best Seller", rating: 4.4, reviewCount: 123, material: "Premium breathable fabric blend with a tailored, easy-care finish", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
  { name: "Men Festive Waistcoat Kurta Set", category: "dresses", gender: "men", price: 2909, oldPrice: 3809, image: "/assets/products/dresses/d8.jpg", tag: "", rating: 4.5, reviewCount: 136, material: "Premium breathable fabric blend with a tailored, easy-care finish", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
  { name: "Floral Wrap Midi Dress", category: "dresses", gender: "women", price: 1339, oldPrice: 2439, image: "/assets/products/dresses/d9.jpg", tag: "New", rating: 4.6, reviewCount: 149, material: "Premium breathable fabric blend with a tailored, easy-care finish", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
  { name: "Satin Slip Evening Dress", category: "dresses", gender: "women", price: 1569, oldPrice: 2269, image: "/assets/products/dresses/d10.jpg", tag: "Best Seller", rating: 4.7, reviewCount: 162, material: "Premium breathable fabric blend with a tailored, easy-care finish", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
  { name: "Casual Denim Shirt Dress", category: "dresses", gender: "women", price: 1799, oldPrice: 2699, image: "/assets/products/dresses/d11.jpg", tag: "Trending", rating: 4.8, reviewCount: 175, material: "Premium breathable fabric blend with a tailored, easy-care finish", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
  { name: "Off-Shoulder Summer Dress", category: "dresses", gender: "women", price: 2029, oldPrice: 3129, image: "/assets/products/dresses/d12.jpg", tag: "", rating: 4.9, reviewCount: 188, material: "Premium breathable fabric blend with a tailored, easy-care finish", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
  { name: "A-Line Cocktail Dress", category: "dresses", gender: "women", price: 2259, oldPrice: 2959, image: "/assets/products/dresses/d13.jpg", tag: "New", rating: 3.8, reviewCount: 201, material: "Premium breathable fabric blend with a tailored, easy-care finish", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
  { name: "Printed Maxi Sundress", category: "dresses", gender: "women", price: 2489, oldPrice: 3389, image: "/assets/products/dresses/d14.jpg", tag: "", rating: 3.9, reviewCount: 214, material: "Premium breathable fabric blend with a tailored, easy-care finish", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
  { name: "Bodycon Party Dress", category: "dresses", gender: "women", price: 2719, oldPrice: 3819, image: "/assets/products/dresses/d15.jpg", tag: "Best Seller", rating: 4.0, reviewCount: 227, material: "Premium breathable fabric blend with a tailored, easy-care finish", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },
  { name: "Chiffon Ruffle Dress", category: "dresses", gender: "women", price: 2949, oldPrice: 3649, image: "/assets/products/dresses/d16.jpg", tag: "", rating: 4.1, reviewCount: 240, material: "Premium breathable fabric blend with a tailored, easy-care finish", sizes: ["XS", "S", "M", "L", "XL", "XXL"] },

  // WATCHES
  { name: "Men Chronograph Steel Watch", category: "watches", gender: "men", price: 1799, oldPrice: 2999, image: "/assets/products/watches/w1.jpg", tag: "New", rating: 3.8, reviewCount: 45, material: "Stainless steel case with a scratch-resistant sapphire-coated glass", sizes: ["Free Size (Adjustable Strap)"] },
  { name: "Men Minimalist Leather Strap Watch", category: "watches", gender: "men", price: 2149, oldPrice: 3549, image: "/assets/products/watches/w2.jpg", tag: "Best Seller", rating: 3.9, reviewCount: 58, material: "Stainless steel case with a scratch-resistant sapphire-coated glass", sizes: ["Free Size (Adjustable Strap)"] },
  { name: "Men Sports Digital Watch", category: "watches", gender: "men", price: 2499, oldPrice: 4099, image: "/assets/products/watches/w3.jpg", tag: "Trending", rating: 4.0, reviewCount: 71, material: "Stainless steel case with a scratch-resistant sapphire-coated glass", sizes: ["Free Size (Adjustable Strap)"] },
  { name: "Men Automatic Skeleton Watch", category: "watches", gender: "men", price: 2849, oldPrice: 4049, image: "/assets/products/watches/w4.jpg", tag: "", rating: 4.1, reviewCount: 84, material: "Stainless steel case with a scratch-resistant sapphire-coated glass", sizes: ["Free Size (Adjustable Strap)"] },
  { name: "Men Titanium Dive Watch", category: "watches", gender: "men", price: 3199, oldPrice: 4599, image: "/assets/products/watches/w5.jpg", tag: "New", rating: 4.2, reviewCount: 97, material: "Stainless steel case with a scratch-resistant sapphire-coated glass", sizes: ["Free Size (Adjustable Strap)"] },
  { name: "Men Classic Analog Watch", category: "watches", gender: "men", price: 3549, oldPrice: 5149, image: "/assets/products/watches/w6.jpg", tag: "", rating: 4.3, reviewCount: 110, material: "Stainless steel case with a scratch-resistant sapphire-coated glass", sizes: ["Free Size (Adjustable Strap)"] },
  { name: "Men Smart Fitness Watch", category: "watches", gender: "men", price: 2099, oldPrice: 3299, image: "/assets/products/watches/w7.jpg", tag: "Best Seller", rating: 4.4, reviewCount: 123, material: "Stainless steel case with a scratch-resistant sapphire-coated glass", sizes: ["Free Size (Adjustable Strap)"] },
  { name: "Men Vintage Pilot Watch", category: "watches", gender: "men", price: 2449, oldPrice: 3849, image: "/assets/products/watches/w8.jpg", tag: "", rating: 4.5, reviewCount: 136, material: "Stainless steel case with a scratch-resistant sapphire-coated glass", sizes: ["Free Size (Adjustable Strap)"] },
  { name: "Women Rose Gold Bracelet Watch", category: "watches", gender: "women", price: 2799, oldPrice: 4399, image: "/assets/products/watches/w9.jpg", tag: "New", rating: 4.6, reviewCount: 149, material: "Stainless steel case with a scratch-resistant sapphire-coated glass", sizes: ["Free Size (Adjustable Strap)"] },
  { name: "Women Pearl Dial Slim Watch", category: "watches", gender: "women", price: 3149, oldPrice: 4349, image: "/assets/products/watches/w10.jpg", tag: "Best Seller", rating: 4.7, reviewCount: 162, material: "Stainless steel case with a scratch-resistant sapphire-coated glass", sizes: ["Free Size (Adjustable Strap)"] },
  { name: "Women Minimal Mesh Strap Watch", category: "watches", gender: "women", price: 3499, oldPrice: 4899, image: "/assets/products/watches/w11.jpg", tag: "Trending", rating: 4.8, reviewCount: 175, material: "Stainless steel case with a scratch-resistant sapphire-coated glass", sizes: ["Free Size (Adjustable Strap)"] },
  { name: "Women Diamond Studded Watch", category: "watches", gender: "women", price: 2049, oldPrice: 3649, image: "/assets/products/watches/w12.jpg", tag: "", rating: 4.9, reviewCount: 188, material: "Stainless steel case with a scratch-resistant sapphire-coated glass", sizes: ["Free Size (Adjustable Strap)"] },
  { name: "Women Ceramic Chain Watch", category: "watches", gender: "women", price: 2399, oldPrice: 3599, image: "/assets/products/watches/w13.jpg", tag: "New", rating: 3.8, reviewCount: 201, material: "Stainless steel case with a scratch-resistant sapphire-coated glass", sizes: ["Free Size (Adjustable Strap)"] },
  { name: "Women Floral Dial Watch", category: "watches", gender: "women", price: 2749, oldPrice: 4149, image: "/assets/products/watches/w14.jpg", tag: "", rating: 3.9, reviewCount: 214, material: "Stainless steel case with a scratch-resistant sapphire-coated glass", sizes: ["Free Size (Adjustable Strap)"] },
  { name: "Women Smart Fitness Band Watch", category: "watches", gender: "women", price: 3099, oldPrice: 4699, image: "/assets/products/watches/w15.jpg", tag: "Best Seller", rating: 4.0, reviewCount: 227, material: "Stainless steel case with a scratch-resistant sapphire-coated glass", sizes: ["Free Size (Adjustable Strap)"] },
  { name: "Women Two-Tone Bangle Watch", category: "watches", gender: "women", price: 3449, oldPrice: 4649, image: "/assets/products/watches/w16.jpg", tag: "", rating: 4.1, reviewCount: 240, material: "Stainless steel case with a scratch-resistant sapphire-coated glass", sizes: ["Free Size (Adjustable Strap)"] },

  // PERFUMES
  { name: "Men Woody Musk Eau De Parfum", category: "perfumes", gender: "men", price: 1199, oldPrice: 1799, image: "/assets/products/perfumes/p1.jpg", tag: "New", rating: 3.8, reviewCount: 45, material: "Long-lasting Eau de Parfum, 18-20% fragrance concentration", sizes: ["50ml", "100ml", "150ml"] },
  { name: "Men Citrus Fresh Cologne", category: "perfumes", gender: "men", price: 1379, oldPrice: 2179, image: "/assets/products/perfumes/p2.jpg", tag: "Best Seller", rating: 3.9, reviewCount: 58, material: "Long-lasting Eau de Parfum, 18-20% fragrance concentration", sizes: ["50ml", "100ml", "150ml"] },
  { name: "Men Leather & Oud Spray", category: "perfumes", gender: "men", price: 1559, oldPrice: 2559, image: "/assets/products/perfumes/p3.jpg", tag: "Trending", rating: 4.0, reviewCount: 71, material: "Long-lasting Eau de Parfum, 18-20% fragrance concentration", sizes: ["50ml", "100ml", "150ml"] },
  { name: "Men Ocean Breeze Cologne", category: "perfumes", gender: "men", price: 1739, oldPrice: 2339, image: "/assets/products/perfumes/p4.jpg", tag: "", rating: 4.1, reviewCount: 84, material: "Long-lasting Eau de Parfum, 18-20% fragrance concentration", sizes: ["50ml", "100ml", "150ml"] },
  { name: "Men Spicy Amber Parfum", category: "perfumes", gender: "men", price: 1919, oldPrice: 2719, image: "/assets/products/perfumes/p5.jpg", tag: "New", rating: 4.2, reviewCount: 97, material: "Long-lasting Eau de Parfum, 18-20% fragrance concentration", sizes: ["50ml", "100ml", "150ml"] },
  { name: "Men Tobacco Vanilla Spray", category: "perfumes", gender: "men", price: 2099, oldPrice: 3099, image: "/assets/products/perfumes/p6.jpg", tag: "", rating: 4.3, reviewCount: 110, material: "Long-lasting Eau de Parfum, 18-20% fragrance concentration", sizes: ["50ml", "100ml", "150ml"] },
  { name: "Men Green Aromatic Cologne", category: "perfumes", gender: "men", price: 2279, oldPrice: 2879, image: "/assets/products/perfumes/p7.jpg", tag: "Best Seller", rating: 4.4, reviewCount: 123, material: "Long-lasting Eau de Parfum, 18-20% fragrance concentration", sizes: ["50ml", "100ml", "150ml"] },
  { name: "Men Midnight Noir Parfum", category: "perfumes", gender: "men", price: 2459, oldPrice: 3259, image: "/assets/products/perfumes/p8.jpg", tag: "", rating: 4.5, reviewCount: 136, material: "Long-lasting Eau de Parfum, 18-20% fragrance concentration", sizes: ["50ml", "100ml", "150ml"] },
  { name: "Women Floral Bloom Eau De Parfum", category: "perfumes", gender: "women", price: 2639, oldPrice: 3639, image: "/assets/products/perfumes/p9.jpg", tag: "New", rating: 4.6, reviewCount: 149, material: "Long-lasting Eau de Parfum, 18-20% fragrance concentration", sizes: ["50ml", "100ml", "150ml"] },
  { name: "Women Vanilla Blush Perfume", category: "perfumes", gender: "women", price: 2819, oldPrice: 3419, image: "/assets/products/perfumes/p10.jpg", tag: "Best Seller", rating: 4.7, reviewCount: 162, material: "Long-lasting Eau de Parfum, 18-20% fragrance concentration", sizes: ["50ml", "100ml", "150ml"] },
  { name: "Women Rose Gold Mist Spray", category: "perfumes", gender: "women", price: 1199, oldPrice: 1999, image: "/assets/products/perfumes/p11.jpg", tag: "Trending", rating: 4.8, reviewCount: 175, material: "Long-lasting Eau de Parfum, 18-20% fragrance concentration", sizes: ["50ml", "100ml", "150ml"] },
  { name: "Women Jasmine Musk Parfum", category: "perfumes", gender: "women", price: 1379, oldPrice: 2379, image: "/assets/products/perfumes/p12.jpg", tag: "", rating: 4.9, reviewCount: 188, material: "Long-lasting Eau de Parfum, 18-20% fragrance concentration", sizes: ["50ml", "100ml", "150ml"] },
  { name: "Women Citrus Bloom Cologne", category: "perfumes", gender: "women", price: 1559, oldPrice: 2159, image: "/assets/products/perfumes/p13.jpg", tag: "New", rating: 3.8, reviewCount: 201, material: "Long-lasting Eau de Parfum, 18-20% fragrance concentration", sizes: ["50ml", "100ml", "150ml"] },
  { name: "Women White Tea Mist", category: "perfumes", gender: "women", price: 1739, oldPrice: 2539, image: "/assets/products/perfumes/p14.jpg", tag: "", rating: 3.9, reviewCount: 214, material: "Long-lasting Eau de Parfum, 18-20% fragrance concentration", sizes: ["50ml", "100ml", "150ml"] },
  { name: "Women Peony Blush Spray", category: "perfumes", gender: "women", price: 1919, oldPrice: 2919, image: "/assets/products/perfumes/p15.jpg", tag: "Best Seller", rating: 4.0, reviewCount: 227, material: "Long-lasting Eau de Parfum, 18-20% fragrance concentration", sizes: ["50ml", "100ml", "150ml"] },
  { name: "Women Amber Oud Parfum", category: "perfumes", gender: "women", price: 2099, oldPrice: 2699, image: "/assets/products/perfumes/p16.jpg", tag: "", rating: 4.1, reviewCount: 240, material: "Long-lasting Eau de Parfum, 18-20% fragrance concentration", sizes: ["50ml", "100ml", "150ml"] },

];

const seedDB = async () => {
  await connectDB();
  Product.deleteMany({});
  Product.insertMany(products);
  console.log(`✅ Seeded ${products.length} products into the local LUXORA database`);
};

seedDB();
